# Generated by Django 3.1.2 on 2020-11-02 15:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0012_auto_20201029_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldParticleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particle_groups', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('trained_model', models.CharField(choices=[('43kGoldDigger', '43kGoldDigger'), ('87kGoldDigger', '87kGoldDigger')], default='87kGoldDigger', max_length=100)),
                ('gold_particle_coordinates', models.FileField(null=True, upload_to='analyzed/coordinates')),
                ('analyzed_image', models.ImageField(null=True, upload_to='analyzed/images')),
                ('histogram_image', models.ImageField(null=True, upload_to='analyzed/histograms')),
            ],
        ),
        migrations.CreateModel(
            name='GoldParticleDataImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_particle_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDapp.goldparticledata')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='Input/')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.FileField(blank=True, upload_to='Mask/')),
            ],
        ),
        migrations.DeleteModel(
            name='EMImage',
        ),
        migrations.AddField(
            model_name='goldparticledataimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDapp.relatedimage'),
        ),
        migrations.AddField(
            model_name='goldparticledataimage',
            name='mask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDapp.relatedmask'),
        ),
    ]
